### ISSUE TITLE
S3 training fixes

### ISSUE THREAD

**Issue by sh0gg0th** [jinchihe/Working#1]
Hey, this relates to the original master at https://github.com/kubeflow/examples/tree/master/mnist which I understand will be soon PRed with your newer examples, but these fixes may still be relevant. I had to make the following fixes to make training on S3 complete successfully:

The job should be pointed to our custom image, too: (this step is mentioned in the local training but not in the S3 part):
`ks param set --env=${KSENV} train image $DOCKER_URL`

The kubeflow namespace has to be mentioned explicitly when creating the environment
```
KSENV=distributed
cd ks_app
ks env add ${KSENV} --namespace=kubeflow
```
and the secret,
```
kubectl create secret generic aws-creds --from-literal=awsAccessKeyID=${AWS_ACCESS_KEY_ID} \
       --from-literal=awsSecretAccessKey=${AWS_SECRET_ACCESS_KEY} --namespace kubeflow
```
otherwise it will go to `default`.

Hope this helps!

**Comment by jinchihe** [comment]
Thanks for the ticket.

1. For image problem, not sure if your env can be get the `gcr.io/kubeflow-examples/mnist/model`, if cannot, yes, that should be set.
2. For namespace, I have a clear description to point to `kubeflow` as below, generally user should be the k8s current context namespace to kubeflow, otherwise all k8s command should be have "-n kubeflow" optuons.

`
In the following instructions we will install our required components to a single namespace.  For these instructions we will assume the chosen namespace is `kubeflow`.
`

**Comment by jinchihe** [comment]
@sh0gg0th For image, I added below description in README.


The default training image is gcr.io/kubeflow-examples/mnist/model:v20190111-v0.2-148-g313770f, if you want to use your custom training image, configurate that as below.
```
kustomize edit set image training-image=$DOCKER_URL:$TAG
```

**Comment by sh0gg0th** [comment]
@jinchihe thanks for getting back to me! the default image, which currently points to gcr.io/kubeflow-examples/mnist/model:v20190111-v0.2-148-g313770f, didn't work for me for some reason.

As for the namespace, maybe something like that?
```
KFNAMESPACE=kubeflow
...
KSENV=distributed
cd ks_app
ks env add ${KSENV} --namespace=$KFNAMESPACE
...
kubectl create secret generic aws-creds --from-literal=awsAccessKeyID=${AWS_ACCESS_KEY_ID} \
       --from-literal=awsSecretAccessKey=${AWS_SECRET_ACCESS_KEY} --namespace $KFNAMESPACE
```
My point is that currently, if you just follow along the example, updating the parameters and pasting the commands into the CLI, you might forget to set the namespace and get confused, especially if you're new to the whole k8/kf environment. Let me know if this makes sense, and thanks for your work!

**Comment by jinchihe** [comment]
For default image, yes, you are right, I already logged a ticket to let release team to refresh the image and then create a PR to update that.

For namespace, the default namespace is `kubeflow` then,  if user want to change that, user can use `kustomize` update that, the `ks` will be dropped, thanks.

**Comment by sh0gg0th** [comment]
@jinchihe great, thank you.
